services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pawgress-client
    volumes:
      - ./client:/client
      - client_node_modules:/client/node_modules
    networks:
      - react-express
    ports:
      - '5173:5173'
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - ./server/.env
    container_name: pawgress-server
    volumes:
      - ./server:/server
      - server_node_modules:/server/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports:
      - '3001:3001'

  mongo:
    restart: always
    image: mongo:8.0.15
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
    ports:
      - '27017:27017'

networks:
  react-express:
  express-mongo:

volumes:
  mongo_data:
  client_node_modules:
  server_node_modules:
